sudo: required

services:
    - docker

language: cpp

before_install:
  - sudo add-apt-repository -y ppa:valhalla-core/valhalla
  - sudo apt-get update -q
  - sudo apt-get install -y valhalla-bin cmake libboost-all-dev libzmq-dev

script:
    - cmake -DCMAKE_BUILD_TYPE=Release . && make
